publish-to-npmjs:
  stage: publish
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/node:18
  rules:
    - if: "$CI_COMMIT_TAG"
  script:
    - |
      bash .gitlab-ci/scripts/bin/publish.sh
      bash ./.gitlab-ci/scripts/bin/slack-status-messages.sh ":rocket: cipherguard-ui $CI_COMMIT_TAG has been published in https://www.npmjs.com/package/cipherguard-ui" "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID"